// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/SpokeChat.tsx": () => import("../components/mockups/SpokeChat.tsx"),
  "./components/mockups/SpokeEventDetail.tsx": () => import("../components/mockups/SpokeEventDetail.tsx"),
  "./components/mockups/SpokeHome.tsx": () => import("../components/mockups/SpokeHome.tsx"),
  "./components/mockups/SpokeInvite.tsx": () => import("../components/mockups/SpokeInvite.tsx")
};
